apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "meals.fullname" . }}
  labels:
    {{- include "meals.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "meals.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "meals.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "meals.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ENV_URL
              value: https://meals-staging.aoe.com/
            - name: SYMFONY_ENV
              value: production
            - name: SYMFONY_DEBUG
              value: "0"
            - name: DB_HOST
              value: localhost
            - name: DB_NAME
              value: db
            - name: DB_USER
              value: db
            - name: DB_PASSWORD
              value: db
            - name: HR_EMAIL
              value: @todo
            - name: KEYCLOAK_CLIENT_ID
              value: aoe-meals
            - name: KEYCLOAK_CLIENT_SECRET
              value: @todo
            - name: PAYPAL_ID
              value: @todo
            - name: PAYPAL_SECRET
              value: @todo
            - name: SMTP_HOST
              value: antispam.aoe.lan
            - name: SMTP_PORT
              value: "25"
            - name: SMTP_AUTH
              value: "off"
            - name: SMTP_USER
              value: noreply-meals
            - name: SMTP_PASSWORD
              value: @todo
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /robots.txt
              port: http
          readinessProbe:
            httpGet:
              path: /robots.txt
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
