imports:
    - { resource: ../commons/all/config.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    profiler:
        enabled: false
    router:
        resource: "%kernel.root_dir%/config/commons/all/routing.yml"
        strict_requirements: true
