security:
    providers:
        active_directory:
            ldap:
              service: app.ldap
              base_dn: %ldap_base_dn%
              search_dn: %ldap_search_dn%
              search_password: %ldap_search_password%
              filter: %ldap_filter%
              default_roles: ROLE_USER, ROLE_LOGIN_LDAP
    firewalls:
        mealz:
            provider: active_directory
            form_login_ldap:
                login_path:  MealzUserBundle_login
                check_path:  MealzUserBundle_checkLogin
                service: app.ldap
                dn_string: %ldap_dn_string%
