security:
    providers:
        oauth_user_provider:
             id: mealz.oauthuserprovider
    firewalls:
        mealz:
            logout:
              path: /logout
              success_handler: Mealz\UserBundle\Provider\LogoutSuccessHandler

    access_control:
        - { path: ^/connect, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/rest, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/oauth/v2/token, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/menu/guest, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/css, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/js, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/images, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/, roles: [ROLE_USER] }

