services:
    #
    # OAuth Service Provider
    #
    Mealz\UserBundle\Provider\OAuthUserProvider:
      class: Mealz\UserBundle\Provider\OAuthUserProvider
      arguments: ["@doctrine"]

    #
    # Logout Success Handler
    #
    Mealz\UserBundle\Provider\LogoutSuccessHandler:
        class: Mealz\UserBundle\Provider\LogoutSuccessHandler
        autowire: false
        arguments:
            $logoutUrl: '%keycloak_logout_endpoint%'
            $baseUri: '%env_url%'
