doctrine:
  dbal:
    url: '%app.db.url%'

    charset: utf8mb4
    default_table_options:
      charset: utf8mb4
      collate: utf8mb4_unicode_ci

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '16'
    use_savepoints: true
  orm:
    enable_lazy_ghost_objects: true
    auto_generate_proxy_classes: true
    controller_resolver:
      # Auto resolve entity in action arguments using the route parameter.
      # Ex.: use "id" parameter in /user/{id}/edit to fetch the User entity,
      #      and pass it as $user argument to UserController::edit(User $user) action.
      # The route and entity property (like id above) must match for mapping to succeed.
      auto_mapping: true
    entity_managers:
      default:
        auto_mapping: true
        report_fields_where_declared: true

#when@test:
#    doctrine:
#        dbal:
#            # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
