# Read the documentation: https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/blob/master/Resources/doc/index.md#step-5-configure-fosoauthserverbundle
fos_oauth_server:
    db_driver: orm

    client_class:        App\Mealz\RestBundle\Entity\Client
    access_token_class:  App\Mealz\RestBundle\Entity\AccessToken
    refresh_token_class: App\Mealz\RestBundle\Entity\RefreshToken
    auth_code_class:     App\Mealz\RestBundle\Entity\AuthCode
    service:
        user_provider: mealz_user.provider.login
