# Default configuration for "MealzMealBundle"
mealz_meal:
    notifier:
        mattermost:
            # Enable/disable sending of meal notifications to mattermost.
            enabled: false

            # Mattermost webhook URL
            webhook_url: 'https://dummy-url'

            # Friendly username displayed in mattermost notifications.
            username: Chef

            # Application name displayed in mattermost notifications.
            app_name: Meals
