stages:
  - deploy

deploy:staging:
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
  image: aoepeople/meals-deployer
  script:
    # for now we just remove the pods and k8s recreate new ones
    # in the future we might set the tag via:
    # kubectl set image deployments/meals app=aoepeople/meals:late

    # usage with compose:
    # docker-compose run deployer kubectl set image deployments/meals app=aoepeople/meals:latest
    - mkdir ~/.kube
    - echo -n "$KUBE_CONFIG" | base64 -d > ~/.kube/config
    - kubectl delete pods --selector=app=meals
    - |
      curl -i -X POST -H 'Content-Type: application/json' \
        -d '{"text": "Deployment of meals-staging.aoe.com done. :white_check_mark:"}' \
        $MATTERMOST_HOOK_URL
