stages:
  - deploy

before_script:
  - mkdir ~/.kube
  - echo -n "$KUBE_CONFIG_STAGING" | base64 -d > ~/.kube/config

deploy:staging:
  stage: deploy
  only:
    - triggers
    - schedules
    - web
  except:
    variables:
      - $RELEASE_TAG
  image: aoepeople/meals-deployer:edge
  script:
    - kubectl delete pods --selector=app=meals
    - sleep 20
    - |
      curl --silent -i -X POST -H 'Content-Type: application/json' \
        -d '{"text": "Deployment of [meals-staging.aoe.com](https://meals-staging.aoe.com/changelog.txt) done. :white_check_mark:"}' \
        $MATTERMOST_HOOK_URL

deploy:production:
  stage: deploy
  image: aoepeople/meals-deployer:edge
  only:
    variables:
      - $RELEASE_TAG
  before_script:
    - mkdir ~/.kube
    - echo -n "$KUBE_CONFIG_PRODUCTION" | base64 -d > ~/.kube/config
  script:
    - kubectl set image deployment/meals app=aoepeople/meals:${RELEASE_TAG} -n team-lemmings-production --record
    - sleep 20
    - |
      curl --silent -i -X POST -H 'Content-Type: application/json' \
        -d '{"text": "Deployment of [meals.aoe.com](https://meals.aoe.com/changelog.txt) done. :white_check_mark:"}' \
        $MATTERMOST_HOOK_URL
