ARG BASE_APP_IMAGE=aoepeople/meals:edge
FROM $BASE_APP_IMAGE

RUN echo "Installing dev dependencies" \
    && apt-get update -y && apt-get install -y \
        git \
        vim \
        --no-install-recommends \
    && curl -L -o /usr/sbin/mhsendmail https://github.com/mailhog/mhsendmail/releases/download/v0.2.0/mhsendmail_linux_amd64 \
    && chmod +x /usr/sbin/mhsendmail \
    && rm -rf /var/lib/apt/lists/* /tmp/* \

RUN echo "Setting up PHP for development..." \
    && sed -i 's/max_execution_time = .*/max_execution_time = 300/' "$PHP_INI_DIR/php.ini" \
    && sed -i 's/;date.timezone =.*/date.timezone= "Europe\/Berlin"/' "$PHP_INI_DIR/php.ini" \
    && sed -i 's/memory_limit = .*/memory_limit = -1/' "$PHP_INI_DIR/php.ini" \
    && printf "[mail function]\nsendmail_path='/usr/sbin/mhsendmail --smtp-addr=mail:1025'\n" > /usr/local/etc/php/conf.d/sendmail.ini \
    && printf "[opcache]\nopcache.enable = 1\nopcache.enable_cli = 1\n" >> "$PHP_INI_DIR/php.ini" \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer2 \
