services:
  app:
    image: aoepeople/meals:beta
    environment:
      - APP_DEBUG=1
      - APP_ENV=staging
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=db_test
      - DB_USER=db
      - DB_PASS=db
      - DB_VERS=5.7
      - SMTP_HOST=mail
      - SMTP_PORT=1025
      - SMTP_AUTH=off
      - IDP_SERVER=https://aoe.login.bare.id/auth/realms/aoe-staging
      - APP_NAME=Meals
      - APP_BASE_URL=http://localhost
      - DB_URL=mysql://db:db@db:3306/db_test?serverVersion=5.7&charset=utf8
      - MERCURE_URL=https://mercure/.well-known/mercure
      - MERCURE_PUBLIC_URL=http://localhost:2443/.well-known/mercure
      - MERCURE_JWT_SECRET="ChangeMeChangeMeChangeMeChangeMe"
      - USE_FORWARDED_HEADERS=1
    depends_on:
      - db
    volumes:
      - shared:/var/www/meals/public/

  db:
    image: "mysql:5.7"
    command: --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    healthcheck:
      test: out=$$(mysqladmin ping -h localhost -P 3306 -u db --password=db 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
    environment:
      - MYSQL_ROOT_PASSWORD=db
      - MYSQL_DATABASE=db_test
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - shared:/var/www/meals/public
      - ./default.conf:/etc/nginx/conf.d/default.conf

  mercure:
    image: dunglas/mercure:v0.14
    restart: unless-stopped
    environment:
      MERCURE_ALLOWED_ORIGINS: http://localhost
      MERCURE_ALLOWED_PUBLISH_ORIGINS: web
      MERCURE_PUBLISHER_JWT_ALG: HS256
      MERCURE_PUBLISHER_JWT_KEY: testing-testing-testing-testing!
      MERCURE_SUBSCRIBER_JWT_ALG: HS256
      MERCURE_SUBSCRIBER_JWT_KEY: testing-testing-testing-testing!
      HTTP_EXPOSE: '8080:8080'
      HTTPS_EXPOSE: '8081:8080'
      SERVER_ADDRESS: 'http://localhost:8080, http://localhost:8080'
    expose:
      - 8080
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./.ddev/caddy/Caddyfile.dev:/etc/caddy/Caddyfile

volumes:
  shared:
    driver: local
  caddy_data:
  caddy_config: