MealzMealBundle_language_switch:
    path:  /language-switch
    defaults: { _controller: App\Mealz\MealBundle\Controller\LanguageController::switch }

MealzMealBundle_api_dashboard:
    path: /api/dashboard
    defaults: { _controller: App\Mealz\MealBundle\Controller\MealController::getDashboardData }

MealzMealBundle_home:
    path:  /
    defaults: { _controller: App\Mealz\MealBundle\Controller\TestController::test }

MealzMealBundle_menu:
  path:  /menu
  defaults: { _controller: App\Mealz\MealBundle\Controller\TestController::test }

MealzMealBundle_categories:
  path: /categories
  defaults: { _controller: App\Mealz\MealBundle\Controller\TestController::test }

MealzMealBundle_timeslots:
  path: /time-slots
  defaults: { _controller: App\Mealz\MealBundle\Controller\TestController::test }

MealzMealBundle_costs:
  path: /costs
  defaults: { _controller: App\Mealz\MealBundle\Controller\TestController::test }

MealzMealBundle_finance:
  path: /finance
  defaults: { _controller: App\Mealz\MealBundle\Controller\TestController::test }

MealzMealBundle_balance:
  path: /balance
  defaults: { _controller: App\Mealz\MealBundle\Controller\TestController::test }

MealzMealBundle_test:
    path: /test
    defaults: { _controller: App\Mealz\MealBundle\Controller\TestController::test }

MealzMealBundle_test:
    path: /test
    defaults: { _controller: App\Mealz\MealBundle\Controller\TestController::test }

MealzMealBundle_test:
    path: /test
    defaults: { _controller: App\Mealz\MealBundle\Controller\TestController::test }

MealzMealBundle_Meal:
    path:  /menu
    defaults: { _controller: App\Mealz\MealBundle\Controller\MealAdminController::list }

MealzMealBundle_Meal_new:
    path:  /menu/{date}/new
    defaults: { _controller: App\Mealz\MealBundle\Controller\MealAdminController::new }
    requirements:
        # format "2014W12" 12th week in 2014
        date: 20\d{2}W[0-5]\d

MealzMealBundle_Meal_edit:
    path:  /menu/{week}/edit
    defaults: { _controller: App\Mealz\MealBundle\Controller\MealAdminController::edit }

MealzMealBundle_Meal_join:
    path:  /menu/{date}/{dish}/join/{profile}
    defaults: { _controller: App\Mealz\MealBundle\Controller\MealController::join, profile: null }
    methods: [POST]
    requirements:
        date: '^\d{4}-\d{2}-\d{2}$'

MealzMealBundle_Meal_accept_offer:
    path: /menu/{date}/{dish}/accept-offer/{profile}
    defaults: { _controller: App\Mealz\MealBundle\Controller\MealController::join, profile: null }
    methods: [GET,POST]
    requirements:
        date: '^\d{4}-\d{2}-\d{2}$'

MealzMealBundle_Meal_offers:
    path: /menu/{date}/{dish}/offers
    defaults: { _controller: App\Mealz\MealBundle\Controller\MealController::getOffers }

MealzMealBundle_Meal_guest:
    path: /menu/guest/{hash}
    defaults: { _controller: App\Mealz\MealBundle\Controller\MealGuestController::joinAsGuest }
    methods: [GET, POST]

MealzMealBundle_Meal_newGuestInvitation:
    path:  /menu/{dayId}/new-guest-invitation
    defaults: { _controller: App\Mealz\MealBundle\Controller\MealGuestController::newGuestInvitation }
    requirements:
        dayId: '[1-9][0-9]*'

MealzMealBundle_Slot:
    path:  /meal/slots
    defaults: { _controller: App\Mealz\MealBundle\Controller\SlotController::listSlots }

MealzMealBundle_Slot_Form_empty:
    path:  /meal/slot/new
    defaults: { _controller: App\Mealz\MealBundle\Controller\SlotController::getEmptyForm }

MealzMealBundle_Slot_new:
    path:  /meal/slot/create
    defaults: { _controller: App\Mealz\MealBundle\Controller\SlotController::new }

MealzMealBundle_Slot_Form_preFilled:
    path:  /meal/slot/{slug}/edit
    defaults: { _controller: App\Mealz\MealBundle\Controller\SlotController::getPreFilledForm }
    methods: [GET]

MealzMealBundle_Slot_edit:
    path:  /meal/slot/{slug}/edit
    defaults: { _controller: App\Mealz\MealBundle\Controller\SlotController::edit }
    methods: [POST]

MealzMealBundle_Slot_updateState:
    path:  /meal/slot/{slug}/update-state
    defaults: { _controller: App\Mealz\MealBundle\Controller\SlotController::updateState }
    methods: [POST]

MealzMealBundle_Slot_delete:
    path:  /meal/slot/{slug}/delete
    defaults: { _controller: App\Mealz\MealBundle\Controller\SlotController::deleteSlot }
    methods: [DELETE]

MealzMealBundle_Participant_update:
    path:  /meal/participation/{participant}/update
    defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::updateCombinedMeal }
    methods: [POST]

MealzMealBundle_Participant_delete:
    path:  /menu/meal/{participant}/delete
    defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::delete }

MealzMealBundle_Participant_swap:
    path: /menu/meal/{participant}/offer-meal
    defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::offerMeal }

MealzMealBundle_Participant_unswap:
    path: /menu/meal/{participant}/cancel-offered-meal
    defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::cancelOfferedMeal }

MealzMealBundle_Participant_updateSlot:
    path: /menu/meal/{date}/update-slot
    defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipationUpdateController::updateSlot }
    methods: [POST]

MealzMealBundle_Meal_isParticipationPending:
    path: /menu/meal/{participant}/isParticipationPending
    defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::isParticipationPending }

MealzMealBundle_DishVariation_new:
    path:  /dish/{id}/variation/new
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishVariationController::new }
    requirements:
      slug: '[1-9][0-9]*'

MealzMealBundle_DishVariation_edit:
    path:  /dish/variation/{slug}/edit
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishVariationController::edit }
    requirements:
      slug: '[1-9][0-9]*'

MealzMealBundle_DishVariation_delete:
    path:  /dish/variation/{slug}/delete
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishVariationController::deleteAction }

MealzMealBundle_Dishes:
  path: /dishes
  defaults: { _controller: App\Mealz\MealBundle\Controller\TestController::test }

MealzMealBundle_Dish:
    path:  /dish
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishController::list }

MealzMealBundle_Dish_Form_empty:
    path:  /dish/form
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishController::getEmptyForm }

MealzMealBundle_Dish_Form_preFilled:
    path:  /dish/form/{slug}
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishController::getPreFilledForm }

MealzMealBundle_Dish_new:
    path:  /dish/new
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishController::new }

MealzMealBundle_Dish_edit:
    path:  /dish/{slug}/edit
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishController::editAction }

MealzMealBundle_Dish_delete:
    path:  /dish/{slug}/delete
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishController::deleteAction }

MealzMealBundle_Category:
    path:  /category
    defaults: { _controller: App\Mealz\MealBundle\Controller\CategoryController::list }

MealzMealBundle_Category_new:
    path:  /category/new
    defaults: { _controller: App\Mealz\MealBundle\Controller\CategoryController::new }

MealzMealBundle_Category_edit:
    path:  /category/{slug}/edit
    defaults: { _controller: App\Mealz\MealBundle\Controller\CategoryController::edit }

MealzMealBundle_Category_delete:
    path:  /category/{slug}/delete
    defaults: { _controller: App\Mealz\MealBundle\Controller\CategoryController::delete }

MealzMealBundle_Category_Form_empty:
    path:  /category/form
    defaults: { _controller: App\Mealz\MealBundle\Controller\CategoryController::getEmptyForm }

MealzMealBundle_Category_Form_preFilled:
    path:  /category/form/{slug}
    defaults: { _controller: App\Mealz\MealBundle\Controller\CategoryController::getPreFilledForm }

MealzMealBundle_Print_participations:
    path: /print/participations
    defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::list }

mealz_meal_edit_participations:
    path: /participations/{week}/edit
    defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::editParticipation }
