MealzMealBundle_home:
    pattern:  /
    defaults: { _controller: "MealzMealBundle:Meal:index", week: %current_week% }

MealzMealBundle_Meal:
    pattern:  /menu
    defaults: { _controller: "MealzMealBundle:Meal:list" }

MealzMealBundle_Meal_week:
    pattern:  /menu/{week}
    defaults: { _controller: "MealzMealBundle:Meal:index" }
    requirements:
        # format "2014W12" 12th week in 2014
        week: 20\d{2}W[0-5]\d

MealzMealBundle_Meal_day:
    pattern:  /menu/{day}
    defaults: { _controller: "MealzMealBundle:Meal:day" }
    requirements:
        # format "2014-02-17" 17th February, 2014
        day: 20\d{2}\-[01]\d\-[0-3]\d

MealzMealBundle_Meal_new:
    pattern:  /menu/new
    defaults: { _controller: "MealzMealBundle:MealAdmin:new" }

MealzMealBundle_Meal_edit:
    pattern:  /menu/{meal}/edit
    defaults: { _controller: "MealzMealBundle:MealAdmin:edit" }

MealzMealBundle_Meal_delete:
    pattern:  /menu/{meal}/delete
    defaults: { _controller: "MealzMealBundle:MealAdmin:delete" }

MealzMealBundle_Meal_show:
    pattern:  /menu/{date}/{dish}
    defaults: { _controller: "MealzMealBundle:Meal:show" }
    requirements:
      date: 20\d{2}\-[01]\d\-[0-3]\d

MealzMealBundle_Meal_join:
    pattern:  /menu/{date}/{dish}/join
    defaults: { _controller: "MealzMealBundle:Meal:join" }

MealzMealBundle_Meal_join_someone:
    pattern:  /menu/{date}/{dish}/join-someone
    defaults: { _controller: "MealzMealBundle:Meal:joinSomeone" }

MealzMealBundle_Participant_new:
    pattern:  /menu/{date}/{dish}/add
    defaults: { _controller: "MealzMealBundle:Participant:new" }

MealzMealBundle_Participant_edit:
    pattern:  /menu/meal/{participant}/edit
    defaults: { _controller: "MealzMealBundle:Participant:edit" }

MealzMealBundle_Participant_delete:
    pattern:  /menu/meal/{participant}/delete
    defaults: { _controller: "MealzMealBundle:Participant:delete" }

MealzMealBundle_Participation_confirm_index:
    pattern:  /menu/meal/confirmation
    defaults: { _controller: "MealzMealBundle:ParticipationConfirmation:index" }

MealzMealBundle_Participation_confirm_index_letter:
    pattern:  /menu/meal/confirmation/{letter}
    defaults: { _controller: "MealzMealBundle:ParticipationConfirmation:indexByLetter" }
    requirements:
      letter: \w{1}

MealzMealBundle_Participant_confirm:
    pattern:  /menu/meal/confirmation/{participant}
    defaults: { _controller: "MealzMealBundle:ParticipationConfirmation:confirmParticipation" }

MealzMealBundle_Dish:
    pattern:  /dish
    defaults: { _controller: "MealzMealBundle:Dish:list" }

MealzMealBundle_Dish_new:
    pattern:  /dish/new
    defaults: { _controller: "MealzMealBundle:DishAdmin:new" }

MealzMealBundle_Dish_edit:
    pattern:  /dish/{slug}/edit
    defaults: { _controller: "MealzMealBundle:DishAdmin:edit" }

MealzMealBundle_Dish_delete:
    pattern:  /dish/{slug}/delete
    defaults: { _controller: "MealzMealBundle:DishAdmin:delete" }