MealzMealBundle_home:
    pattern:  /
    defaults: { _controller: "MealzMealBundle:Meal:index" }

MealzMealBundle_Meal:
    pattern:  /menu
    defaults: { _controller: "MealzMealBundle:Meal:list" }

MealzMealBundle_Meal_add:
    pattern:  /menu/new
    defaults: { _controller: "MealzMealBundle:MealAdmin:new" }

MealzMealBundle_Meal_edit:
    pattern:  /menu/{meal}/edit
    defaults: { _controller: "MealzMealBundle:MealAdmin:edit" }

MealzMealBundle_Meal_delete:
    pattern:  /menu/{meal}/delete
    defaults: { _controller: "MealzMealBundle:MealAdmin:delete" }

MealzMealBundle_Meal_show:
    pattern:  /menu/{meal}
    defaults: { _controller: "MealzMealBundle:Meal:show" }

MealzMealBundle_Meal_join:
    pattern:  /menu/{meal}/join
    defaults: { _controller: "MealzMealBundle:Meal:join" }

MealzMealBundle_Participant_new:
    pattern:  /menu/{meal}/add
    defaults: { _controller: "MealzMealBundle:Participant:new" }

MealzMealBundle_Participant_edit:
    pattern:  /menu/meal/{participant}/edit
    defaults: { _controller: "MealzMealBundle:Participant:edit" }

MealzMealBundle_Participant_delete:
    pattern:  /menu/meal/{participant}/delete
    defaults: { _controller: "MealzMealBundle:Participant:delete" }

MealzMealBundle_Dish:
    pattern:  /dish
    defaults: { _controller: "MealzMealBundle:Dish:list" }

MealzMealBundle_Dish_new:
    pattern:  /dish/new
    defaults: { _controller: "MealzMealBundle:DishAdmin:new" }

MealzMealBundle_Dish_edit:
    pattern:  /dish/{dish}/edit
    defaults: { _controller: "MealzMealBundle:DishAdmin:edit" }

MealzMealBundle_Dish_delete:
    pattern:  /dish/{dish}/delete
    defaults: { _controller: "MealzMealBundle:DishAdmin:delete" }
