MealzMealBundle_language_switch:
    path:  /language-switch
    defaults: { _controller: "MealzMealBundle:Language:switch" }

MealzMealBundle_home:
    path:  /
    defaults: { _controller: "MealzMealBundle:Meal:index" }

MealzMealBundle_Meal:
    path:  /menu
    defaults: { _controller: "MealzMealBundle:MealAdmin:list" }

MealzMealBundle_Meal_new:
    path:  /menu/{date}/new
    defaults: { _controller: "MealzMealBundle:MealAdmin:new" }
    requirements:
        # format "2014W12" 12th week in 2014
        date: 20\d{2}W[0-5]\d

MealzMealBundle_Meal_edit:
    path:  /menu/{week}/edit
    defaults: { _controller: "MealzMealBundle:MealAdmin:edit" }

MealzMealBundle_Meal_join:
    path:  /menu/{date}/{dish}/join/{profile}
    defaults: { _controller: "MealzMealBundle:Meal:join", profile: null }

MealzMealBundle_Participant_delete:
    path:  /menu/meal/{participant}/delete
    defaults: { _controller: "MealzMealBundle:Participant:delete" }

MealzMealBundle_Participant_swap:
    path: /menu/meal/{participant}/swap
    defaults: { _controller: "MealzMealBundle:Participant:swap" }

MealzMealBundle_Participant_unswap:
    path: /menu/meal/{participant}/unswap
    defaults: { _controller: "MealzMealBundle:Participant:swap" }

MealzMealBundle_Meal_accept_offer:
    path: /menu/{date}/{dish}/accept-offer/{profile}
    defaults: { _controller: "MealzMealBundle:Meal:join", profile: null }

MealzMealBundle_Meal_updateOffers:
    path: /menu/meal/update-offers
    defaults: { _controller: "MealzMealBundle:Meal:updateOffers" }

MealzMealBundle_Meal_isParticipationPending:
    path: /menu/meal/{participant}/isParticipationPending
    defaults: { _controller: "MealzMealBundle:Participant:isParticipationPending" }

MealzMealBundle_DishVariation:
    path:  /dish/{slug}/variation/
    defaults: { _controller: "mealz_meal.controller.dish_variation:listAction" }
    requirements:
      slug: '[1-9][0-9]*'

MealzMealBundle_DishVariation_new:
    path:  /dish/{slug}/variation/new
    defaults: { _controller: "mealz_meal.controller.dish_variation:newAction" }
    requirements:
      slug: '[1-9][0-9]*'

MealzMealBundle_DishVariation_edit:
    path:  /dish/variation/{slug}/edit
    defaults: { _controller: "mealz_meal.controller.dish_variation:editAction" }
    requirements:
      slug: '[1-9][0-9]*'

MealzMealBundle_DishVariation_delete:
    path:  /dish/variation/{slug}/delete
    defaults: { _controller: "mealz_meal.controller.dish_variation:deleteAction" }
    requirements:
      slug: '[1-9][0-9]*'

MealzMealBundle_Dish:
    path:  /dish
    defaults: { _controller: "mealz_meal.controller.dish:listAction" }

MealzMealBundle_Dish_Form_empty:
    path:  /dish/form
    defaults: { _controller: "mealz_meal.controller.dish:getEmptyFormAction" }

MealzMealBundle_Dish_Form_preFilled:
    path:  /dish/form/{slug}
    defaults: { _controller: "mealz_meal.controller.dish:getPreFilledFormAction" }

MealzMealBundle_Dish_new:
    path:  /dish/new
    defaults: { _controller: "mealz_meal.controller.dish:newAction" }

MealzMealBundle_Dish_edit:
    path:  /dish/{slug}/edit
    defaults: { _controller: "mealz_meal.controller.dish:editAction" }

MealzMealBundle_Dish_delete:
    path:  /dish/{slug}/delete
    defaults: { _controller: "mealz_meal.controller.dish:deleteAction" }

MealzMealBundle_Category:
    path:  /category
    defaults: {_controller: "mealz_meal.controller.category:listAction"}

MealzMealBundle_Category_new:
    path:  /category/new
    defaults: { _controller: "mealz_meal.controller.category:newAction" }

MealzMealBundle_Category_edit:
    path:  /category/{slug}/edit
    defaults: {_controller: "mealz_meal.controller.category:editAction"}

MealzMealBundle_Category_delete:
    path:  /category/{slug}/delete
    defaults: {_controller: "mealz_meal.controller.category:deleteAction"}

MealzMealBundle_Category_Form_empty:
    path:  /category/form
    defaults: { _controller: "mealz_meal.controller.category:getEmptyFormAction" }

MealzMealBundle_Category_Form_preFilled:
    path:  /category/form/{slug}
    defaults: { _controller: "mealz_meal.controller.category:getPreFilledFormAction" }

MealzMealBundle_Print_participations:
    path: /print/participations
    defaults: { _controller: "MealzMealBundle:Participant:list" }

mealz_meal_edit_participations:
    path: /participations/{week}/edit
    defaults: { _controller: "MealzMealBundle:Participant:editParticipation" }

MealzMealBundle_Meal_guest:
    path: /menu/guest/{hash}
    defaults: { _controller: "MealzMealBundle:Meal:guest" }

MealzMealBundle_Meal_newGuestInvitation:
    path:  /menu/{dayId}/new-guest-invitation
    defaults: { _controller: "MealzMealBundle:Meal:newGuestInvitation" }
    requirements:
      dayId: '[1-9][0-9]*'
