MealzMealBundle_language_switch:
    path:  /language-switch
    defaults: { _controller: App\Mealz\MealBundle\Controller\LanguageController::switch }

MealzMealBundle_api_dashboard:
    path: /api/dashboard
    defaults: { _controller: App\Mealz\MealBundle\Controller\ApiController::getDashboardData }
    methods: [GET]

MealzMealBundle_guest_api_dashboard:
  path: /guest/api/dashboard
  defaults: { _controller: App\Mealz\MealBundle\Controller\ApiController::getDashboardData }
  methods: [ GET ]

MealzMealBundle_api_transactions:
  path: /api/transactions
  defaults: { _controller: App\Mealz\MealBundle\Controller\ApiController::getTransactionData }
  methods: [GET]

MealzMealBundle_api_timeslots:
  path: /api/timeslots
  defaults: { _controller: App\Mealz\MealBundle\Controller\ApiController::getTimeSlotData }
  methods: [GET]

MealzMealBundle_api_update-slot:
  path: /api/update-slot
  defaults: { _controller: App\Mealz\MealBundle\Controller\SlotController::updateSlot }
  methods: [POST]

MealzMealBundle_api_create-slot:
  path: /api/create-slot
  defaults: { _controller: App\Mealz\MealBundle\Controller\SlotController::createSlot }
  methods: [POST]

MealzMealBundle_api_delete-slot:
  path: /api/delete-slot
  defaults: { _controller: App\Mealz\MealBundle\Controller\SlotController::deleteSlot }
  methods: [POST]

MealzMealBundle_api_environmentals:
  path: /api/environmentals
  defaults: { _controller: App\Mealz\MealBundle\Controller\ApiController::getEnvironmentVars }
  methods: [GET]

MealzMealBundle_home:
    path:  /
    defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }

MealzMealBundle_menu:
  path:  /menu
  defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }

MealzMealBundle_categories:
  path: /categories
  defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }

MealzMealBundle_timeslots:
  path: /time-slots
  defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }

MealzMealBundle_costs:
  path: /costs
  defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }

MealzMealBundle_finance:
  path: /finance
  defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }

MealzMealBundle_Meal_guest:
  path: /guest/{hash}
  defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }
  methods: [ GET, POST ]

MealzMealBundle_balance:
  path: /balance
  defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }

MealzMealBundle_Meal:
    path:  /menu
    defaults: { _controller: App\Mealz\MealBundle\Controller\MealAdminController::list }

MealzMealBundle_Meal_edit:
    path:  /menu/{week}/edit
    defaults: { _controller: App\Mealz\MealBundle\Controller\MealAdminController::edit }

MealzMealBundle_api_join_Meal:
  path: /api/join-meal
  defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::joinMeal }
  methods: [POST]

MealzMealBundle_api_join_Meal_Guest:
  path: /guest/api/join-meal
  defaults: { _controller: App\Mealz\MealBundle\Controller\MealGuestController::joinAsGuest }
  methods: [ POST ]

MealzMealBundle_api_leave_Meal:
  path: /api/leave-meal
  defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::leaveMeal }
  methods: [POST]

MealzMealBundle_api_offer_meal:
  path: /api/offer-meal
  defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::offerMeal }
  methods: [POST]

MealzMealBundle_api_cancel_offer:
  path: /api/cancel-offer
  defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::cancelOfferedMeal }
  methods: [POST]

MealzMealBundle_api_update_selected_Slot:
  path: /api/update-selected-slot
  defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipationUpdateController::updateSlot }
  methods: [ POST ]

MealzMealBundle_api_invitationdata:
  path: /api/guest-invitation-{guestInvitationId}
  defaults: { _controller: App\Mealz\MealBundle\Controller\ApiController::getGuestData }
  methods: [ GET ]

MealzMealBundle_Meal_offers:
    path: /menu/{date}/{dish}/offers
    defaults: { _controller: App\Mealz\MealBundle\Controller\MealController::getOffers }

MealzMealBundle_Meal_newGuestInvitation:
    path:  /menu/{dayId}/new-guest-invitation
    defaults: { _controller: App\Mealz\MealBundle\Controller\MealGuestController::newGuestInvitation }
    requirements:
        dayId: '[1-9][0-9]*'

MealzMealBundle_Participant_update:
    path:  /meal/participation/{participant}/update
    defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::updateCombinedMeal }
    methods: [POST]

MealzMealBundle_Participant_swap:
    path: /menu/meal/{participant}/offer-meal
    defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::offerMeal }

MealzMealBundle_Participant_unswap:
    path: /menu/meal/{participant}/cancel-offered-meal
    defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::cancelOfferedMeal }

MealzMealBundle_Participant_updateSlot:
    path: /menu/meal/{date}/update-slot
    defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipationUpdateController::updateSlot }
    methods: [POST]

MealzMealBundle_Meal_isParticipationPending:
    path: /menu/meal/{participant}/isParticipationPending
    defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::isParticipationPending }

MealzMealBundle_DishVariation_new:
    path:  /dish/{id}/variation/new
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishVariationController::new }
    requirements:
      slug: '[1-9][0-9]*'

MealzMealBundle_DishVariation_edit:
    path:  /dish/variation/{slug}/edit
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishVariationController::edit }
    requirements:
      slug: '[1-9][0-9]*'

MealzMealBundle_DishVariation_delete:
    path:  /dish/variation/{slug}/delete
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishVariationController::deleteAction }

MealzMealBundle_Dishes:
  path: /dishes
  defaults: { _controller: App\Mealz\MealBundle\Controller\TestController::renderIndex }

MealzMealBundle_Dish:
    path:  /dish
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishController::list }

MealzMealBundle_Dish_Form_empty:
    path:  /dish/form
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishController::getEmptyForm }

MealzMealBundle_Dish_Form_preFilled:
    path:  /dish/form/{slug}
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishController::getPreFilledForm }

MealzMealBundle_Dish_new:
    path:  /dish/new
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishController::new }

MealzMealBundle_Dish_edit:
    path:  /dish/{slug}/edit
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishController::editAction }

MealzMealBundle_Dish_delete:
    path:  /dish/{slug}/delete
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishController::deleteAction }

MealzMealBundle_api_categories:
    path: /api/categories
    defaults: { _controller: App\Mealz\MealBundle\Controller\CategoryController::getCategoriesData }
    methods: [GET]

MealzMealBundle_Category_create:
    path:  /api/category/create
    defaults: { _controller: App\Mealz\MealBundle\Controller\CategoryController::createCategory }
    methods: [POST]

MealzMealBundle_Category_edit:
    path:  /api/category/{id}/edit
    defaults: { _controller: App\Mealz\MealBundle\Controller\CategoryController::editCategory }
    methods: [POST]

MealzMealBundle_Category_delete:
    path:  /api/category/{id}/delete
    defaults: { _controller: App\Mealz\MealBundle\Controller\CategoryController::deleteCategory }

MealzMealBundle_Print_participations:
    path: /print/participations
    defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }

MealzMealBundle_Print_participations_api:
  path: /api/print/participations
  defaults: { _controller: App\Mealz\MealBundle\Controller\ApiController::list }
  methods: [ GET ]

mealz_meal_edit_participations:
    path: /participations/{week}/edit
    defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::editParticipation }

MealzMealBundle_Show_participations:
    path: /show/participations
    defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }

MealzMealBundle_api_meals_next_three_days:
    path: /api/meals/nextThreeDays
    defaults: { _controller: App\Mealz\MealBundle\Controller\ApiController::getNextThreeDays }
    methods: [ GET ]