MealzMealBundle_api_dashboard:
    path: /api/dashboard
    defaults: { _controller: App\Mealz\MealBundle\Controller\ApiController::getDashboardData }
    methods: [GET]

MealzMealBundle_guest_api_dashboard:
  path: /guest/api/dashboard
  defaults: { _controller: App\Mealz\MealBundle\Controller\ApiController::getDashboardData }
  methods: [ GET ]

MealzMealBundle_api_transactions:
  path: /api/transactions
  defaults: { _controller: App\Mealz\MealBundle\Controller\ApiController::getTransactionData }
  methods: [GET]

MealzMealBundle_api_slots:
  path: /api/slots
  defaults: { _controller: App\Mealz\MealBundle\Controller\SlotController::getTimeSlots }
  methods: [GET]

MealzMealBundle_api_slots_update:
  path: /api/slots/{slug}
  defaults: { _controller: App\Mealz\MealBundle\Controller\SlotController::update }
  methods: [PUT]

MealzMealBundle_api_slots_create:
  path: /api/slots
  defaults: { _controller: App\Mealz\MealBundle\Controller\SlotController::new }
  methods: [POST]

MealzMealBundle_api_slots_delete:
  path: /api/slots/{slug}
  defaults: { _controller: App\Mealz\MealBundle\Controller\SlotController::delete }
  methods: [DELETE]

MealzMealBundle_api_environmentals:
  path: /api/environmentals
  defaults: { _controller: App\Mealz\MealBundle\Controller\ApiController::getEnvironmentVars }
  methods: [GET]

MealzMealBundle_home:
    path:  /
    defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }

MealzMealBundle_menu:
  path:  /menu/{week}
  defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }

MealzMealBundle_menu_create:
  path:  /menu/{week}/create
  defaults:
    _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    path: /weeks
    permanent: true

MealzMealBundle_weeks:
  path:  /weeks
  defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }

MealzMealBundle_categories:
  path: /categories
  defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }

MealzMealBundle_timeslots:
  path: /time-slots
  defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }

MealzMealBundle_events:
  path: /events
  defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }

MealzMealBundle_costs:
  path: /costs
  defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }

MealzMealBundle_cash_register:
  path: /cash-register
  defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }

MealzMealBundle_costs_settlement_confirm:
  path: /costs/settlement/confirm/{hash}
  defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }

MealzMealBundle_finance:
  path: /finance
  defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }

MealzMealBundle_Meal_guest:
  path: /guest/{hash}
  defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }
  methods: [ GET, POST ]

MealzMealBundle_Meal_guest_event:
  path: /guest/event/{hash}
  defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }
  methods: [ GET, POST ]

MealzMealBundle_balance:
  path: /balance
  defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }

MealzMealBundle_api_weeks:
    path: /api/weeks
    defaults: { _controller: App\Mealz\MealBundle\Controller\MealAdminController::getWeeks }
    methods: [GET]

MealzMealBundle_api_weeks_new:
    path: /api/weeks/{date}
    defaults: { _controller: App\Mealz\MealBundle\Controller\MealAdminController::new }
    methods: [POST]
    requirements:
        # format "2014W12" 12th week in 2014
        date: 20\d{2}W[0-5]\d

MealzMealBundle_api_weeks_empty:
    path: /api/weeks/{date}
    defaults: { _controller: App\Mealz\MealBundle\Controller\MealAdminController::getEmptyWeek }
    methods: [GET]
    requirements:
        # format "2014W12" 12th week in 2014
        date: 20\d{2}W[0-5]\d

MealzMealBundle_api_menu_edit:
    path: /api/menu/{id}
    defaults: { _controller: App\Mealz\MealBundle\Controller\MealAdminController::edit }
    methods: [PUT]

MealzMealBundle_api_week_lockDates:
    path: /api/week/lockdates/{id}
    defaults: { _controller: App\Mealz\MealBundle\Controller\MealAdminController::getLockDateTimeForWeek }
    methods: [GET]

MealzMealBundle_api_participant_add:
    path: /api/participation/{profile}/{meal}
    defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::add }
    methods: [PUT]

MealzMealBundle_api_participant_remove:
    path: /api/participation/{profile}/{meal}
    defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::remove }
    methods: [DELETE]

MealzMealBundle_api_is_participanting:
    path: /api/participation/{meal}
    defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::isParticipating}
    methods: [GET]

MealzMealBundle_Meal_count:
    path: /api/meals/count
    defaults: { _controller: App\Mealz\MealBundle\Controller\MealAdminController::count }
    methods: [GET]

MealzMealBundle_api_join_Meal:
  path: /api/meal/participation
  defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::joinMeal }
  methods: [POST]

MealzMealBundle_api_join_Meal_Guest:
  path: /api/guest/meal/participation
  defaults: { _controller: App\Mealz\MealBundle\Controller\MealGuestController::joinAsGuest }
  methods: [POST]

MealzMealBundle_api_leave_Meal:
  path: /api/meal/participation
  defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::leaveMeal }
  methods: [DELETE]

MealzMealBundle_api_offer_meal:
  path: /api/meal/offer
  defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::offerMeal }
  methods: [POST]

MealzMealBundle_api_cancel_offer:
  path: /api/meal/offer
  defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::cancelOfferedMeal }
  methods: [DELETE]

MealzMealBundle_api_update_selected_Slot:
  path: /api/participation/slot
  defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipationUpdateController::updateSlot }
  methods: [PUT]

MealzMealBundle_api_invitationdata:
  path: /api/guest-invitation-{guestInvitationId}
  defaults: { _controller: App\Mealz\MealBundle\Controller\ApiController::getGuestData }
  methods: [ GET ]

MealzMealBundle_api_event_invitation_data:
  path: /api/event/invitation/{invitationId}
  defaults: { _controller: App\Mealz\MealBundle\Controller\MealGuestController::getEventInvitationData }
  methods: [ GET ]

MealzMealBundle_api_event_invitation_join:
  path: /api/event/invitation/{invitationId}
  defaults: { _controller: App\Mealz\MealBundle\Controller\MealGuestController::joinEventAsGuest }
  methods: [ POST ]

MealzMealBundle_api_events:
  path: /api/events
  defaults: { _controller: App\Mealz\MealBundle\Controller\EventController::getEventList }
  methods: [ GET ]

MealzMealBundle_api_events_new:
  path: /api/events
  defaults: { _controller: App\Mealz\MealBundle\Controller\EventController::new }
  methods: [ POST ]

MealzMealBundle_api_events_update:
  path: /api/events/{slug}
  defaults: { _controller: App\Mealz\MealBundle\Controller\EventController::update }
  methods: [ PUT ]

MealzMealBundle_api_events_delete:
  path: /api/events/{slug}
  defaults: { _controller: App\Mealz\MealBundle\Controller\EventController::delete }
  methods: [ DELETE ]

MealzMealBundle_api_events_join:
  path: /api/events/participation/{date}/{eventId}
  defaults: { _controller: App\Mealz\MealBundle\Controller\EventController::join }
  methods: [ POST ]

MealzMealBundle_api_events_leave:
  path: /api/events/participation/{date}/{eventId}
  defaults: { _controller: App\Mealz\MealBundle\Controller\EventController::leave }
  methods: [ DELETE ]

MealzMealBundle_Meal_api_guest_event_invitation:
    path:  /event/invitation/{dayId}
    defaults: { _controller: App\Mealz\MealBundle\Controller\MealGuestController::newGuestEventInvitation }
    requirements:
        dayId: '[1-9][0-9]*'

MealzMealBundle_Meal_offers:
    path: /menu/{date}/{dish}/offers
    defaults: { _controller: App\Mealz\MealBundle\Controller\MealController::getOffers }

MealzMealBundle_Meal_newGuestInvitation:
    path:  /menu/{dayId}/new-guest-invitation
    defaults: { _controller: App\Mealz\MealBundle\Controller\MealGuestController::newGuestInvitation }
    requirements:
        dayId: '[1-9][0-9]*'

MealzMealBundle_Participant_update:
    path:  /meal/participation/{participant}/update
    defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::updateCombinedMeal }
    methods: [POST]

MealzMealBundle_Participant_swap:
    path: /menu/meal/{participant}/offer-meal
    defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::offerMeal }

MealzMealBundle_Participant_unswap:
    path: /menu/meal/{participant}/cancel-offered-meal
    defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::cancelOfferedMeal }

MealzMealBundle_Participant_updateSlot:
    path: /menu/meal/{date}/update-slot
    defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipationUpdateController::updateSlot }
    methods: [POST]

MealzMealBundle_Meal_isParticipationPending:
    path: /menu/meal/{participant}/isParticipationPending
    defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::isParticipationPending }

MealzMealBundle_api_DishVariation_new:
    path:  /api/dishes/{slug}/variation
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishVariationController::new }
    methods: [POST]

MealzMealBundle_api_DishVariation_update:
    path:  /api/dishes/variation/{slug}
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishVariationController::update }
    methods: [PUT]

MealzMealBundle_api_DishVariation_delete:
    path:  /api/dishes/variation/{slug}
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishVariationController::delete }
    methods: [DELETE]

MealzMealBundle_Dishes:
  path: /dishes
  defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }

MealzMealBundle_api_dishes:
    path:  /api/dishes
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishController::getDishes }
    methods: [GET]

MealzMealBundle_Dish_new:
    path:  /api/dishes
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishController::new }
    methods: [POST]

MealzMealBundle_Dish_update:
    path:  /api/dishes/{slug}
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishController::update }
    methods: [PUT]

MealzMealBundle_Dish_delete:
    path:  /api/dishes/{slug}
    defaults: { _controller: App\Mealz\MealBundle\Controller\DishController::delete }
    methods: [DELETE]

MealzMealBundle_api_categories:
    path: /api/categories
    defaults: { _controller: App\Mealz\MealBundle\Controller\CategoryController::getCategories }
    methods: [GET]

MealzMealBundle_api_categories_new:
    path:  /api/categories
    defaults: { _controller: App\Mealz\MealBundle\Controller\CategoryController::new }
    methods: [POST]

MealzMealBundle_Category_update:
    path:  /api/categories/{slug}
    defaults: { _controller: App\Mealz\MealBundle\Controller\CategoryController::update }
    methods: [PUT]

MealzMealBundle_Category_delete:
    path:  /api/categories/{slug}
    defaults: { _controller: App\Mealz\MealBundle\Controller\CategoryController::delete }
    methods: [DELETE]

MealzMealBundle_Print_participations:
    path: /print/participations
    defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }

MealzMealBundle_Print_participations_api:
  path: /api/print/participations
  defaults: { _controller: App\Mealz\MealBundle\Controller\ApiController::list }
  methods: [ GET ]

MealzMealBundle_Print_participations_api_date:
  path: /api/print/participations/{date}
  defaults: { _controller: App\Mealz\MealBundle\Controller\ApiController::listByDate }
  methods: [ GET ]
  requirements:
        # format yyyy-mm-dd with
        date: ^(20)\d\d-\d\d-\d\d$

MealzMealBundle_participations_api_date:
  path: /api/participations/day/{date}
  defaults: { _controller: App\Mealz\MealBundle\Controller\ApiController::listParticipantsByDate }
  methods: [ GET ]
  requirements:
        # format yyyy-mm-dd with
        date: ^(20)\d\d-\d\d-\d\d$

mealz_meal_edit_participations:
    path: /participations/{week}/edit
    defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }

MealzMealBundle_api_participations:
    path: /api/participations/{week}
    defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::getParticipationsForWeek }
    methods: [ GET ]

MealzMealBundle_api_event_participations:
    path: /api/participations/event/{date}
    defaults: { _controller: App\Mealz\MealBundle\Controller\EventController::getEventParticipants }
    methods: [ GET ]

MealzMealBundle_api_non_participating:
    path: /api/participations/{week}/abstaining
    defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::getProfilesWithoutParticipation }
    methods: [ GET ]

MealzMealBundle_api_participation_combi:
  path: /api/participations/combi/{meal}
  defaults: { _controller: App\Mealz\MealBundle\Controller\ParticipantController::getCombiForMeal }
  methods: [ GET ]

MealzMealBundle_Show_participations:
    path: /show/participations
    defaults: { _controller: App\Mealz\MealBundle\Controller\FrontendController::renderIndex }

MealzMealBundle_api_meals_next_three_days:
    path: /api/meals/nextThreeDays
    defaults: { _controller: App\Mealz\MealBundle\Controller\ApiController::getNextThreeDays }
    methods: [ GET ]