MealzMealBundle_home:
    pattern:  /
    defaults: { _controller: "MealzMealBundle:Meal:index" }

MealzMealBundle_Meal_list:
    pattern:  /menu
    defaults: { _controller: "MealzMealBundle:Meal:list" }

MealzMealBundle_Meal_show:
    pattern:  /menu/{meal}
    defaults: { _controller: "MealzMealBundle:Meal:show" }