MealzMealBundle_home:
    pattern:  /
    defaults: { _controller: "MealzMealBundle:Meal:index" }

MealzMealBundle_Meal_list:
    pattern:  /menu
    defaults: { _controller: "MealzMealBundle:Meal:list" }

MealzMealBundle_Meal_show:
    pattern:  /menu/{meal}
    defaults: { _controller: "MealzMealBundle:Meal:show" }

MealzMealBundle_Meal_join:
    pattern:  /menu/{meal}/join
    defaults: { _controller: "MealzMealBundle:Participant:join" }

MealzMealBundle_Meal_leave:
    pattern:  /menu/{meal}/leave
    defaults: { _controller: "MealzMealBundle:Participant:leave" }

MealzMealBundle_Meal_comment:
    pattern:  /menu/{meal}/comment
    defaults: { _controller: "MealzMealBundle:Participant:comment" }