parameters:
  mealz_meal.twig_extension.doorman.class: App\Mealz\MealBundle\Twig\Extension\Doorman
  mealz_meal.twig_extension.link.class: App\Mealz\MealBundle\Twig\Extension\Link
  mealz_meal.link.class: App\Mealz\MealBundle\Service\Link
  mealz_meal.http_header_utility.class: App\Mealz\MealBundle\Service\HttpHeaderUtility
  mealz_meal.workday.class: App\Mealz\MealBundle\Service\Workday

  mealz_meal.event_listener.participant_persistence.class: App\Mealz\MealBundle\EventListener\ParticipantPersistenceListener
  mealz_meal.event_listener.localisation.class: App\Mealz\MealBundle\EventListener\LocalisationListener

services:
  mealz_meal.doorman: '@App\Mealz\MealBundle\Service\Doorman'

  mealz_meal.link:
    class: '%mealz_meal.link.class%'
    arguments: [ '@router' ]

  mealz_meal.http_header_utility:
    class: '%mealz_meal.http_header_utility.class%'
    calls:
      - [setLocales, [[en, de]]]

  mealz_meal.workday:
    class: '%mealz_meal.workday.class%'
    calls:
      - [setDayBlacklist, [['01-01', '05-01', '10-31', '12-24', '12-25', '12-26', '12-27', '12-28', '12-29', '12-30', '12-31']]]

#  mealz_meal.dish:
#    class: App\Mealz\MealBundle\Entity\Dish

  mealz_meal.dish_variation:
    class: App\Mealz\MealBundle\Entity\DishVariation
    arguments: ['@mealz_meal.dish']

  mealz_meal.day:
    class: App\Mealz\MealBundle\Entity\Day

  mealz_user.profile:
    class: App\Mealz\UserBundle\Entity\Profile

  mealz_meal.guest_invitation:
    class: App\Mealz\MealBundle\Entity\GuestInvitation
    arguments: ['@mealz_user.profile', '@mealz_meal.day']

  mealz_meal.event_listener.participant_persistence:
    class: '%mealz_meal.event_listener.participant_persistence.class%'
    tags:
        - { name: doctrine.event_listener, event: prePersist }
        - { name: doctrine.event_listener, event: preUpdate }

  mealz_meal.event_listener.localisation:
    class: '%mealz_meal.event_listener.localisation.class%'
    arguments: ['@mealz_meal.http_header_utility']
    tags:
      # set locale in request
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 12 }

  mealz_meal.event_listener.localisation.entity:
    class: App\Mealz\MealBundle\EventListener\EntityLocalisationListener
    arguments: ['@mealz_meal.http_header_utility', '@request_stack']
    tags:
      # set locale in request
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
      # set locale in dish entities
      - { name: doctrine.event_listener, event: postLoad }

  mealz_meal.repository.participant:
    class: App\Mealz\MealBundle\Entity\ParticipantRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - MealzMealBundle:Participant
    autowire: false
    autoconfigure: false
  App\Mealz\MealBundle\Entity\ParticipantRepository: '@mealz_meal.repository.participant'

  mealz_meal.factory.localized_repository:
    class: App\Mealz\MealBundle\Service\LocalizedRepositoryFactory
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@mealz_meal.event_listener.localisation'

  mealz_meal.repository.category:
    class: App\Mealz\MealBundle\Entity\CategoryRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - 'MealzMealBundle:Category'

  mealz_meal.repository.abstract.localized:
    abstract: true
    factory: ['@mealz_meal.factory.localized_repository', createLocalizedRepository]

  mealz_meal.repository.dish:
    class: App\Mealz\MealBundle\Entity\DishRepository
    parent: mealz_meal.repository.abstract.localized
#    autowire: false
#    autoconfigure: false
#    public: false
    arguments:
      - 'MealzMealBundle:Dish'
  App\Mealz\MealBundle\Entity\DishRepository: '@mealz_meal.repository.dish'

  App\Mealz\MealBundle\Entity\WeekRepository:
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - 'MealzMealBundle:Week'

  mealz_meal.repository.dish_variation:
    class: App\Mealz\MealBundle\Entity\DishVariationRepository
    parent: mealz_meal.repository.abstract.localized
    autowire: true
    autoconfigure: false
    public: false
    arguments:
      - 'MealzMealBundle:DishVariation'

  mealz_meal.form.type.dish_selector_creator:
        class: App\Mealz\MealBundle\Form\Type\DishSelectorCreatorType
        arguments: []
        tags:
            - { name: form.type, alias: dish_selector_creator }

  mealz_meal.form.type.hidden_entity:
        class: App\Mealz\MealBundle\Form\Type\EntityHiddenType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
           - { name: form.type, alias: entity_hidden }

  mealz_meal.form.type.meal:
    class: App\Mealz\MealBundle\Form\MealAdmin\MealForm
    arguments: ['@mealz_meal.repository.dish']
    tags:
      - { name: form.type }

  mealz_meal.form.dish:
    class: App\Mealz\MealBundle\Form\Dish\DishForm
    arguments: ['%mealz.meal.price%']
    tags:
      - { name: form.type }

  mealz_meal.form.dishvariation:
    class: App\Mealz\MealBundle\Form\Dish\DishVariationForm
    arguments: ['%mealz.meal.price%']
    tags:
      - { name: form.type }

  mealz_meal.form.type.day:
    class: App\Mealz\MealBundle\Form\MealAdmin\DayForm
    arguments: ['@doctrine.orm.entity_manager']
    tags:
      - { name: form.type }

  validator.meal.dish:
    class: App\Mealz\MealBundle\Validator\Constraints\DishConstraintValidator
    arguments: ['@doctrine.orm.entity_manager']
    tags:
      - { name: validator.constraint_validator, alias: validator_meal_dish }

  mealz_meal.controller.base:
    abstract: true
    calls:
      - [setContainer, ['@service_container']]

  mealz_meal.controller.baseList:
    abstract: true
    calls:
      - [setContainer, ['@service_container']]

  mealz_meal.controller.category:
    class: App\Mealz\MealBundle\Controller\CategoryController
    parent: mealz_meal.controller.baseList
    autowire: true
    autoconfigure: false
    public: true
    calls:
      - [setRepository, ['@mealz_meal.repository.category']]
      - [setEntityName, ['Category']]

  mealz_meal.controller.dish:
    class: App\Mealz\MealBundle\Controller\DishController
    parent: mealz_meal.controller.baseList
    autowire: true
    autoconfigure: false
    public: true
    calls:
      - [setRepository, ['@mealz_meal.repository.dish']]
      - [setEntityName, ['Dish']]

  mealz_meal.controller.dish_variation:
    class: App\Mealz\MealBundle\Controller\DishVariationController
    parent: mealz_meal.controller.base
    autowire: true
    autoconfigure: false
    public: true
#    calls:
#      - [setRepository, ['@mealz_meal.repository.dish_variation']]
#      - [setEntityName, ['DishVariation']]

  mealz_meal.monolog.processor.psr:
      class: Monolog\Processor\PsrLogMessageProcessor
      tags:
          - { name: monolog.processor }

  mealz_meal.notifier.mattermost:
    class: App\Mealz\MealBundle\Service\Notification\MattermostService
    lazy: true
    arguments:
      $httpClient: '@http_client'
      $logger: '@logger'
      $enabled: false
      $webhookURL: ''
      $username: ''
      $appName: ''

  App\Mealz\MealBundle\Service\Notification\MattermostService: '@mealz_meal.notifier.mattermost'
