parameters:
  mealz_meal.twig_extension.doorman.class: Mealz\MealBundle\Twig\Extension\Doorman
  mealz_meal.doorman.class: Mealz\MealBundle\Service\Doorman

services:

  mealz_meal.doorman:
    class: %mealz_meal.doorman.class%
    arguments: [ @security.context ]

  mealz_meal.twig_extension.doorman:
    class: %mealz_meal.twig_extension.doorman.class%
    arguments: [ @mealz_meal.doorman ]
    tags:
      - { name: twig.extension }