parameters:
  mealz_meal.twig_extension.doorman.class: Mealz\MealBundle\Twig\Extension\Doorman
  mealz_meal.twig_extension.link.class: Mealz\MealBundle\Twig\Extension\Link
  mealz_meal.doorman.class: Mealz\MealBundle\Service\Doorman
  mealz_meal.link.class: Mealz\MealBundle\Service\Link
  mealz_meal.http_header_utility.class: Mealz\MealBundle\Service\HttpHeaderUtility

  mealz_meal.event_listener.participant_persistence.class: Mealz\MealBundle\EventListener\ParticipantPersistenceListener
  mealz_meal.event_listener.localisation.class: Mealz\MealBundle\EventListener\LocalisationListener

services:

  mealz_meal.doorman:
    class: %mealz_meal.doorman.class%
    arguments: [ @security.context ]

  mealz_meal.twig_extension.doorman:
    class: %mealz_meal.twig_extension.doorman.class%
    arguments: [ @mealz_meal.doorman ]
    tags:
      - { name: twig.extension }

  mealz_meal.link:
    class: %mealz_meal.link.class%
    arguments: [ @router ]

  mealz_meal.twig_extension.link:
    class: %mealz_meal.twig_extension.link.class%
    arguments: [ @mealz_meal.link ]
    tags:
      - { name: twig.extension }

  mealz_meal.http_header_utility:
    class: %mealz_meal.http_header_utility.class%
    calls:
      - [setLocales, [[%locale%, en, de]]]

  mealz_meal.event_listener.participant_persistence:
    class: %mealz_meal.event_listener.participant_persistence.class%
    tags:
        - { name: doctrine.event_listener, event: prePersist }
        - { name: doctrine.event_listener, event: preUpdate }

  mealz_meal.event_listener.localisation:
    class: %mealz_meal.event_listener.localisation.class%
    arguments: [@request_stack, @mealz_meal.http_header_utility]
    tags:
      # set locale in request
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
      # set locale in dish entities
      - { name: doctrine.event_listener, event: postLoad }

  mealz_meal.form.type.dish_selector_creator:
        class: Mealz\MealBundle\Form\Type\DishSelectorCreatorType
        arguments: []
        tags:
            - { name: form.type, alias: dish_selector_creator }