parameters:
  mealz_meal.twig_extension.doorman.class: Mealz\MealBundle\Twig\Extension\Doorman
  mealz_meal.twig_extension.link.class: Mealz\MealBundle\Twig\Extension\Link
  mealz_meal.doorman.class: Mealz\MealBundle\Service\Doorman
  mealz_meal.link.class: Mealz\MealBundle\Service\Link
  mealz_meal.http_header_utility.class: Mealz\MealBundle\Service\HttpHeaderUtility
  mealz_meal.workday.class: Mealz\MealBundle\Service\Workday

  mealz_meal.event_listener.participant_persistence.class: Mealz\MealBundle\EventListener\ParticipantPersistenceListener
  mealz_meal.event_listener.localisation.class: Mealz\MealBundle\EventListener\LocalisationListener

services:

  mealz_meal.doorman:
    class: %mealz_meal.doorman.class%
    arguments: [ @security.context, %mealz.lock_toggle_participation_at%]

  mealz_meal.twig_extension.doorman:
    class: %mealz_meal.twig_extension.doorman.class%
    arguments: [ @mealz_meal.doorman ]
    tags:
      - { name: twig.extension }

  mealz_meal.link:
    class: %mealz_meal.link.class%
    arguments: [ @router ]

  mealz_meal.twig_extension.link:
    class: %mealz_meal.twig_extension.link.class%
    arguments: [ @mealz_meal.link ]
    tags:
      - { name: twig.extension }

  mealz_meal.twig_extension.isParticipant:
    class: Mealz\MealBundle\Twig\Extension\Participation
    tags:
      - { name: twig.extension }

  mealz_meal.http_header_utility:
    class: %mealz_meal.http_header_utility.class%
    calls:
      - [setLocales, [[%locale%, en, de]]]

  mealz_meal.workday:
    class: %mealz_meal.workday.class%
    calls:
      - [setDayBlacklist, [['01-01', '05-01', '10-31', '12-24', '12-25', '12-26', '12-27', '12-28', '12-29', '12-30', '12-31']]]

  mealz_meal.event_listener.participant_persistence:
    class: %mealz_meal.event_listener.participant_persistence.class%
    tags:
        - { name: doctrine.event_listener, event: prePersist }
        - { name: doctrine.event_listener, event: preUpdate }

  mealz_meal.event_listener.localisation:
    class: %mealz_meal.event_listener.localisation.class%
    arguments: [@mealz_meal.http_header_utility]
    tags:
      # set locale in request
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 12 }

  mealz_meal.event_listener.localisation.entity:
    class: Mealz\MealBundle\EventListener\EntityLocalisationListener
    arguments: [@mealz_meal.http_header_utility, @request_stack]
    tags:
      # set locale in request
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
      # set locale in dish entities
      - { name: doctrine.event_listener, event: postLoad }

  mealz_meal.repository.participant:
    class: Mealz\MealBundle\Entity\ParticipantRepository
    factory_service: doctrine.orm.entity_manager
    factory_method: getRepository
    arguments:
        - 'MealzMealBundle:Participant'

  mealz_meal.factory.localized_repository:
    class: Mealz\MealBundle\Service\LocalizedRepositoryFactory
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@mealz_meal.event_listener.localisation'

  mealz_meal.repository.category:
    class: Mealz\MealBundle\Entity\CategoryRepository
    factory_service: doctrine.orm.entity_manager
    factory_method: getRepository
    arguments:
      - 'MealzMealBundle:Category'

  mealz_meal.repository.abstract.localized:
    abstract: true
    factory: ['@mealz_meal.factory.localized_repository', createLocalizedRepository]

  mealz_meal.repository.dish:
    class: Mealz\MealBundle\Entity\DishRepository
    parent: mealz_meal.repository.abstract.localized
    arguments:
      - 'MealzMealBundle:Dish'

  mealz_meal.form.type.dish_selector_creator:
        class: Mealz\MealBundle\Form\Type\DishSelectorCreatorType
        arguments: []
        tags:
            - { name: form.type, alias: dish_selector_creator }

  mealz_meal.form.type.meals_participant:
        class: Mealz\MealBundle\Form\MealParticipantForm
        arguments: []
        tags:
            - { name: form.type, alias: participant }

  mealz_meal.form.type.meal:
    class: Mealz\MealBundle\Form\Type\MealType
    arguments: ['@mealz_meal.repository.dish']
    tags:
      - { name: form.type }

  mealz_meal.form.dish:
    class: Mealz\MealBundle\Form\DishForm
    arguments: ['%mealz.meal.price%']
    tags:
      - { name: form.type }

  mealz_meal.form.type.day:
    class: Mealz\MealBundle\Form\Type\DayType
    arguments: ['@doctrine.orm.entity_manager']
    tags:
      - { name: form.type }

  validator.meal.dish:
    class: Mealz\MealBundle\Validator\Constraints\DishConstraintValidator
    arguments: ['@doctrine.orm.entity_manager']
    tags:
      - { name: validator.constraint_validator, alias: validator_meal_dish }

  mealz_meal.controller.baseList:
    abstract: true
    calls:
      - [setContainer, ["@service_container"]]

  mealz_meal.controller.category:
    class: Mealz\MealBundle\Controller\CategoryController
    parent: mealz_meal.controller.baseList
    calls:
      - [setRepository, ["@mealz_meal.repository.category"]]
      - [setEntityName, ["Category"]]

  mealz_meal.controller.dish:
    class: Mealz\MealBundle\Controller\DishController
    parent: mealz_meal.controller.baseList
    calls:
      - [setRepository, ["@mealz_meal.repository.dish"]]
      - [setEntityName, ["Dish"]]

  mealz_meal.monolog.processor.psr:
      class: Monolog\Processor\PsrLogMessageProcessor
      tags:
          - { name: monolog.processor }
