imports:
    - { resource: ../commons/development/config.yml }
    - { resource: parameters.yml }

framework:
    profiler:
        enabled: false
    router:
        resource: "%kernel.root_dir%/config/commons/all/routing.yml"
        strict_requirements: true
