parameters:
    database_name:     mealz
    database_user:     mealz
    database_password: mealz

    database_name_testing: mealz_test
    database_user_testing: mealz_test
    database_password_testing: mealz_test

    secret:            ThisTokenIsNotSoSecretChangeIt


