security:
    encoders:
        Mealz\UserBundle\Entity\Login:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        default:
          chain:
              providers: [database, in_memory]
        #ldap:
          # an extended imag_ldap.security.user.provider
          # id: mealz_user.security.user.provider
        database:
          entity: { class: Mealz\UserBundle\Entity\Login, property: username }
        in_memory:
          memory:
            users:
              confirmation:
                password: confirm
                roles: 'ROLE_CONFIRMATION'

    firewalls:
        mealz:
            pattern: ^/
            anonymous: ~
            provider: default
            form_login:
                login_path:  MealzUserBundle_login
                check_path:  MealzUserBundle_checkLogin
            logout:
                path:   MealzUserBundle_logout
                target: /
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/menu/meal/confirmation, roles: ROLE_CONFIRMATION }