parameters:
  database_host: db
  database_name: db
  database_user: db
  database_password: db

  database_name_testing: mealz_test
  database_user_testing: mealz_test
  database_password_testing: mealz_test

  secret: ThisTokenIsNotSoSecretChangeIt

  hr_email: 'team-lemmings@aoe.com'

  reverse_proxy: ~
