xopn_mealz_for_zombies_zombies:
    resource: "@MealzUserBundle/Resources/config/routing.yml"
    prefix:   /

xopn_mealz_for_zombies_mealz:
    resource: "@MealzMealBundle/Resources/config/routing.yml"
    prefix:   /