xopn_mealz_for_zombies_zombies:
    resource: "@XopnMealzForZombiesZombiesBundle/Resources/config/routing.yml"
    prefix:   /

xopn_mealz_for_zombies_mealz:
    resource: "@XopnMealzForZombiesMealzBundle/Resources/config/routing.yml"
    prefix:   /