security:
    encoders:
        Mealz\UserBundle\Entity\Zombie:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        user:
            entity: { class: MealzUserBundle:Zombie, property: username }

    firewalls:
        mealz:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path:  MealzUserBundle_login
                check_path:  MealzUserBundle_checkLogin
            logout:
                path:   MealzUserBundle_logout
                target: /
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
