#!/bin/sh
set -e

echo "Setup Apache configuration"
envsubst < "/container/apache/meals-vhost.conf" > "/etc/apache2/sites-enabled/meals.conf"

cp "/container/apache/dump_io.conf" "/etc/apache2/conf-available/dump_io.conf"
cp "/container/apache/certs/apache.crt" "/etc/ssl/certs/apache.crt"
cp "/container/apache/certs/apache.key" "/etc/ssl/private/apache.key"

a2enmod ssl
a2enmod dump_io

a2enconf dump_io

echo "Setup PHP configuration"
envsubst < "/container/php.ini" > "/usr/local/etc/php/conf.d/_meals.ini"

echo "Wait for MySQL and execute migrations"
/usr/local/bin/wait-for db:3306 -t 60 -- /var/www/html/bin/console doctrine:migrations:migrate --no-interaction

if [ "${APP_ENV}" = "staging" ]; then
  echo "Load data fixtures"
  /var/www/html/bin/console doctrine:fixtures:load -n
fi

echo "Fix file permissions"
chown -R www-data:www-data /var/www/html/var

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

echo "Starting Apache"
exec "$@"
