#!/bin/sh
set -e

echo "Check database"
/container/scripts/wait-for "${DB_HOST}:${DB_PORT}" -t 60 -- echo "Database is available"

# execute system initialization scripts
"${APP_ROOT}/scripts/init.sh"

exec docker-php-entrypoint "$@"
