# Default configuration for "MealzMealBundle"
mealz_meal:
    notifier:
        mattermost:
            # Enable/disable sending of meal notifications to mattermost.
            enabled: true

            # Mattermost webhook URL
            webhook_url: https://messages.aoe.com/hooks/f9nb161oppro8nin15zhtrgqqh
