monolog:
  channels: [balance]
  handlers:
    main:
      type: group
      members: [stderr, file]
      channels: ["!event", "!php", "!doctrine", "!balance"]
    stderr:
      type: stream
      path: php://stderr
      level: debug
    file:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
    doctrine:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.doctrine.log"
      level: debug
      channels: ["doctrine"]
    deprecation:
      type: stream
      level: debug
      path: '%kernel.logs_dir%/%kernel.environment%.deprecation.log'
      channels: ["php"]
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine"]
    balance:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.admin-balance-change.log"
      level:  info
      channels: ["balance"]
