parameters:
    env_url: "https://meals-staging.aoe.com/"
    hr_email: "team-lemmings@aoe.com"

    database_host:     db
    database_name:     db
    database_user:     db
    database_password: db

    database_name_testing: db
    database_user_testing: db
    database_password_testing: db

    secret: ThisTokenIsNotSoSecretChangeIt
    keycloak_client_id: "aoe-meals-staging"
    keycloak_client_secret: "d38d66b2-9090-47a8-8ecf-63a607667674"
    
    reverse_proxy: ~
