parameters:
    xopn.doctrine_file_listener.class: Xopn\DoctrineFileBundle\Service\FileListener
    xopn.doctrine_file_manager.class: Xopn\DoctrineFileBundle\Service\FileManager

services:
    xopn.doctrine_file_listener:
        class: %xopn.doctrine_file_listener.class%
        arguments: [ @annotation_reader, @xopn.doctrine_file_manager ]
        tags:
            -  { name: doctrine.event_listener, event: preUpdate }
            -  { name: doctrine.event_listener, event: prePersist }
            -  { name: doctrine.event_listener, event: preDelete }
            -  { name: doctrine.event_listener, event: postLoad }

    xopn.doctrine_file_manager:
        class: %xopn.doctrine_file_manager.class%
        arguments: [ %kernel.root_dir%/.. ]
        calls:
            # only needed to resolve parameters from configuration
            - [setContainer, [@service_container]]