#!/usr/bin/env php
<?php

// grant write access to group
umask(0002);

set_time_limit(0);

require_once __DIR__ . '/bootstrap.php.cache';
require_once __DIR__ . '/AppKernel.php';
require_once __DIR__ . '/AppEnvironment.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), null);
if ($env) {
    $environment = AppEnvironment::fromString($env);
} else {
    $environment = AppEnvironment::fromDefault();
}

$debug = getenv('SYMFONY_DEBUG') !== '0' &&
    !$input->hasParameterOption(array('--no-debug', '')) &&
    $environment->getEnvironment() !== 'prod';

if ($debug) {
    Debug::enable();
}

$kernel = new AppKernel($environment, $debug);
$application = new Application($kernel);
$application->run($input);
