#!/bin/bash

# path where include scripts are located, i.e. .ddev/commands/include
INCLUDE_PATH=$(dirname "$(dirname "${BASH_SOURCE[0]}")")/include

source "${INCLUDE_PATH}"/func.sh


#########################
# Application Setup
#########################
echo_header "Installing application dependencies..."
ddev composer install --no-interaction

#########################
# Database Setup
#########################
echo_header "Configuring database..."
ddev setup-db

#########################
# Frontend Setup
#########################
echo_header "Generating frontend assets..."
ddev build-fe
