hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [main]

    # https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/2-configuring_resource_owners.md
    resource_owners:
        meals:
            type:                oauth2
            client_id:           '%env(IDP_CLIENT_ID)%'
            client_secret:       '%env(IDP_CLIENT_SECRET)%'
            access_token_url:    '%app.idp.endpoint.access_token%'
            authorization_url:   '%app.idp.endpoint.auth_token%'
            infos_url:           '%app.idp.endpoint.user_token%'
            user_response_class: HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse
            paths:
                identifier: id
                nickname:   preferred_username
                realname:   name
                firstname:  given_name
                lastname:   family_name
            options:
                use_bearer_authorization: true
    http:
        client: httplug.client.hwi_special
