hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [mealz]

    # https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/2-configuring_resource_owners.md
    resource_owners:
        meals:
            type:                oauth2
            client_id:           '%env(KEYCLOAK_CLIENT_ID)%'
            client_secret:       '%env(KEYCLOAK_CLIENT_SECRET)%'
            access_token_url:    '%app.keycloak.endpoint.access_token%'
            authorization_url:   '%app.keycloak.endpoint.auth_token%'
            infos_url:           '%app.keycloak.endpoint.user_token%'
            user_response_class: HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse
            paths:
                identifier: id
                nickname:   preferred_username
                realname:   name
            options:
                use_bearer_authorization: true
    http:
        client: httplug.client.hwi_special
