security:
    firewalls:
        main:
            oauth:
                resource_owners:
                    # Redirect URL called by identity provider on successful authentication
                    meals: meals_login
                login_path: /connect/meals
                use_forward: true
                failure_path: /connect/meals

                oauth_user_provider:
                    service: mealz.oauthuserprovider
            logout:
                path:   MealzUserBundle_logout
                # where to redirect after logout
                target: /
