<?php

namespace Mealz\AccountingBundle\Entity;

use Mealz\UserBundle\Entity\Profile;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends \Doctrine\ORM\EntityRepository
{
    const COLUMN_NAME = 'amount';

    /**
     * Get total amount of transactions. Prevent unnecessary ORM mapping.
     *
     * @param Profile $profile
     * @return float
     * @throws \Doctrine\DBAL\DBALException
     */
    public function getTotalAmount(Profile $profile)
    {
        $sql = 'SELECT SUM(amount) as :amount FROM transaction WHERE user = :user AND successful = 1';
        $stmt = $this->getEntityManager()
            ->getConnection()
            ->prepare($sql);
        $stmt->bindValue('user', $profile->getName(), 'string');
        $stmt->bindValue('amount', self::COLUMN_NAME, 'string');
        $stmt->execute();
        $amount = $stmt->fetch()[self::COLUMN_NAME];
        return floatval($amount);
    }
}
