XopnMealzForZombiesMealzBundle_home:
    pattern:  /
    defaults: { _controller: "XopnMealzForZombiesMealzBundle:Meal:index" }

XopnMealzForZombiesMealzBundle_Meal_list:
    pattern:  /menu
    defaults: { _controller: "XopnMealzForZombiesMealzBundle:Meal:list" }

XopnMealzForZombiesMealzBundle_Meal_show:
    pattern:  /menu/{meal}
    defaults: { _controller: "XopnMealzForZombiesMealzBundle:Meal:show" }