imports:
    - { resource: security.yml }
    - { resource: parameters.yml }

framework:
    #esi:             ~
    translator:      { fallback: en}
    secret:          "%secret%"
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        cookie_lifetime: 604800
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    profiler: { only_exceptions: true }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'MealzTemplateBundle:Form:fields.html.twig'
    globals:
        # @TODO: rename lock_toggle_participation_at
        lock_toggle_participation_at: %mealz.lock_toggle_participation_at%
        wallet: "@mealz_accounting.wallet"
        paypal_id: "%paypal_id%"
        paypal_secret: "%paypal_secret%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: true
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    # version caching for css and js assets
    workers:
        cache_busting: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            timestampable: true

monolog:
    channels: ["balance"]
    handlers:
        balance:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.admin-balance-change.log"
            level:  info
            channels: [balance]
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
            channels: [!balance]
        console:
            type:   console
            bubble: false
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        exception_wrapper_handler: Mealz\RestBundle\Handler\ExceptionWrapperHandler
        formats:
            xml: true
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    exception:
        enabled: true
    routing_loader:
        default_format: json

fos_oauth_server:
    db_driver:           orm
    client_class:        Mealz\RestBundle\Entity\Client
    access_token_class:  Mealz\RestBundle\Entity\AccessToken
    refresh_token_class: Mealz\RestBundle\Entity\RefreshToken
    auth_code_class:     Mealz\RestBundle\Entity\AuthCode
    service:
        user_provider: mealz_user.provider.login

creatissimo_mattermost:
    appname: "Meals"
    username: "DevChef"
    webhook: https://messages.aoe.com/hooks/f9nb161oppro8nin15zhtrgqqh
    channel:
    iconUrl: "http://deploy.mealz.itg.de2.dc.aoe.lan/images/chef_bot.png"
    environments:
        devbox:
            enable: true
            terminate:
                enable: false
                exclude_exitcode: [0]
            exception:
                enable: false
                trace: false

        deploy:
            enable: true
            terminate:
                enable: false
                exclude_exitcode: [0]
            exception:
                enable: false
                trace: false

        production:
            appname: "Meals"
            username: "Chef"
            webhook: https://messages.aoe.com/hooks/hh5od44xgp8p5rax9uzmgxffmh
            iconUrl: "http://meals.aoe.com/images/chef_bot.png"
            enable: true
            terminate:
                enable: false
                exclude_exitcode: [0]
            exception:
                enable: false
                trace: false
                exclude_class:
                    - Symfony\Component\HttpKernel\Exception\NotFoundHttpException

hwi_oauth:
    firewall_names: [mealz]
    resource_owners:
        meals:
            type:                oauth2
            client_id:           '%keycloak_client_id%'
            client_secret:       '%keycloak_client_secret%'
            access_token_url:    '%keycloak_access_token_endpoint%'
            authorization_url:   '%keycloak_auth_token_endpoint%'
            infos_url:           '%keycloak_user_token_endpoint%'
            user_response_class: HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse
            paths:
                identifier: id
                nickname:   preferred_username
                realname:   name
            options:
                use_bearer_authorization: true
    http_client:
            verify_peer: false
            ignore_errors: false
