parameters:
    # @TODO: rename mealz.lock_toggle_participation_at
    mealz.lock_toggle_participation_at: '-1 day 16:00'
    mealz.meal.price: 3.40
    mealz.meal.search_timestamp: '2000-01-01'
    mealz.meal.new_flag_counter: 2

    database_driver:   mysqli
    database_host:     127.0.0.1
    database_port:

    pdo.db_options:
        db_table:    session
        db_id_col:   session_id
        db_data_col: session_value
        db_time_col: session_time

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en

    hr_email: 'replaced_by_deployment'
    paypal_id: "Acbj_OdOFasvxF6I2mJrrQTMN3vuSE65WbnyRkBBCMF5U32g63sXbCbPflPDA8sMDttBUsbLW7r59OtE"
    paypal_secret: "EPdo7UqDZTUjfpeurN0LDrEIptyEs9yYYL6Jb08rPQ7yHcYY0-6vSNyf0OnT3zDDY8JUb4cw52L4zfwZ"

    keycloak_access_token_endpoint: 'https://login.aoe.com/auth/realms/aoe/protocol/openid-connect/token'
    keycloak_auth_token_endpoint:   'https://login.aoe.com/auth/realms/aoe/protocol/openid-connect/auth'
    keycloak_logout_endpoint:       'https://login.aoe.com/auth/realms/aoe/protocol/openid-connect/logout'
    keycloak_user_token_endpoint:   'https://login.aoe.com/auth/realms/aoe/protocol/openid-connect/userinfo'
    keycloak_openid_server:         'https://login.aoe.com/auth/realms/aoe'
    keycloak_client_id:             'replaced_by_deployment'
    keycloak_client_secret:         'replaced_by_deployment'

    env_url:                        'replaced_by_deployment'
    reverse_proxy:                  'replaced_by_deployment'
