xopn_mealz_for_zombies_zombies:
    resource: "@MealzUserBundle/Resources/config/routing.yml"
    prefix:   /

xopn_mealz_for_zombies_mealz:
    resource: "@MealzMealBundle/Resources/config/routing.yml"
    prefix:   /

xopn_mealz_for_zombies_accounting:
    resource: "@MealzAccountingBundle/Resources/config/routing.yml"
    prefix:   /

# resized images
_liip_imagine:
  resource: "@LiipImagineBundle/Resources/config/routing.xml"