security:
    encoders:
        Mealz\UserBundle\Entity\Login:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        oauth_user_provider:
             id: Mealz\UserBundle\Provider\OAuthUserProvider
    firewalls:
        mealz:
            oauth:
                resource_owners:
                    meals: meals_login
                login_path: /connect/meals
                use_forward: true
                failure_path: MealzUserBundle_logout

                oauth_user_provider:
                    service: mealz.oauthuserprovider
            logout:
              path: /logout
              success_handler: Mealz\UserBundle\Provider\LogoutSuccessHandler
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        rest:
            pattern:    ^/rest
            fos_oauth:  true
            stateless:  true
            anonymous:  false

    access_control:
        - { path: ^/login, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/connect, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/rest, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/oauth/v2/token, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/, roles: [ROLE_OAUTH_USER] }
