security:
    encoders:
        Mealz\UserBundle\Entity\Login:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        oauth_user_provider:
             id: Mealz\UserBundle\Provider\OAuthUserProvider
    firewalls:
        mealz:
            pattern: ^/
            anonymous: ~
            oauth:
                resource_owners:
                    mealz: "/login/check-meals"
                login_path: MealzUserBundle_login
                use_forward: false
                failure_path: MealzUserBundle_login

                oauth_user_provider:
                    service: Mealz\UserBundle\Provider\OAuthUserProvider
            logout:
                path:   MealzUserBundle_logout
                target: /
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        rest:
            pattern:    ^/rest
            fos_oauth:  true
            stateless:  true
            anonymous:  false

    access_control:
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
