# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    mealz_provider.class: Mealz\UserBundle\Provider\OAuthUserProvider
    #parameter_name: value

services:
    #
    # OAuth Service Provider
    #
    Mealz\UserBundle\Provider\OAuthUserProvider:
      class: "%mealz_provider.class%"
      arguments:
        - @doctrine
