parameters:
    mealz_accounting.participant_list_factory.class: Mealz\AccountingBundle\ParticipantList\ParticipantListFactory
    mealz_accounting.wallet.class: Mealz\AccountingBundle\Service\Wallet

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false
    mealz_accounting.participant_list_factory:
        class: %mealz_accounting.participant_list_factory.class%
        arguments:
            - '@mealz_meal.repository.participant'

    mealz_accounting.repository.transaction:
        class: Mealz\AccountingBundle\Entity\TransactionRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - 'MealzAccountingBundle:Transaction'

    mealz_accounting.wallet:
        class: %mealz_accounting.wallet.class%
        arguments:
            - '@mealz_meal.repository.participant'
            - '@mealz_accounting.repository.transaction'

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    mealz_accounting.form.payment.cash:
      class: Mealz\AccountingBundle\Form\CashPaymentAdminForm
      arguments: ['@doctrine.orm.entity_manager']
      tags:
        - { name: form.type }
