parameters:
    mealz_accounting.participant_list_factory.class: Mealz\AccountingBundle\ParticipantList\ParticipantListFactory
    mealz_accounting.wallet.class: Mealz\AccountingBundle\Service\Wallet

services:

    mealz_accounting.participant_list_factory:
        class: %mealz_accounting.participant_list_factory.class%
        arguments:
            - '@mealz_meal.repository.participant'

    mealz_accounting.repository.transaction:
        class: Mealz\AccountingBundle\Entity\TransactionRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - 'MealzAccountingBundle:Transaction'

    mealz_accounting.wallet:
        class: %mealz_accounting.wallet.class%
        arguments:
            - '@mealz_meal.repository.participant'
            - '@mealz_accounting.repository.transaction'

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    mealz_accounting.form.payment.cash:
      class: Mealz\AccountingBundle\Form\CashPaymentAdminForm
      arguments: ['@doctrine.orm.entity_manager']
      tags:
        - { name: form.type }