<?php

namespace Mealz\UserBundle\Provider;

use Doctrine\ORM\EntityManager;
use IMAG\LdapBundle\Manager\LdapManagerUserInterface;
use IMAG\LdapBundle\Provider\LdapUserProvider as ImagLdapUserProvider;
use Mealz\UserBundle\User\LdapUser;

/**
 * extend the default ldapUserProvider to load the profile of the logged in user
 */
class LdapUserProvider extends ImagLdapUserProvider {

	/**
	 * @var EntityManager
	 */
	protected $entityManager;

	public function __construct(EntityManager $entityManager, LdapManagerUserInterface $ldapManager, $bindUsernameBefore = false, $userClass)
	{
		$this->entityManager = $entityManager;
		parent::__construct($ldapManager, $bindUsernameBefore, $userClass); // TODO: Change the autogenerated stub
	}


	/**
	 * after the user has been loaded, also load the profile for the user
	 *
	 * {@inheritdoc}
	 */
	public function loadUserByUsername($username) {
		$ldapUser = parent::loadUserByUsername($username);

		// load profile for $ldapUser
		if($ldapUser instanceof LdapUser) {
			$profile = $this->entityManager->find('MealzUserBundle:Profile', $ldapUser->getUserName());
			$ldapUser->setProfile($profile);
		}

		return $ldapUser;
	}


}