#!/bin/bash

function main() {
  local CMD=$1

  case "${CMD}" in
  'migrate')
    execMigrateTestDb "$@"
    ;;
  'tests')
    execTests "$@"
    ;;
  *)
    showUsage
    ;;
  esac
}

function execTests() {
  vendor/bin/phpunit -c tests/phpunit.xml.dist -- "${@:2}"
}

function  execMigrateTestDb() {
  bin/console doctrine:schema:update --env=test --force
}

function showUsage() {
  cat <<-'EOM'
Usage:
  ddev run [command] options

Commands:
  tests               Run unit and functional test
EOM
}

main "$@"
