#!/bin/bash

# fully drop (if exists) and create application DB schema
./bin/console doctrine:schema:drop --full-database --force --no-interaction
./bin/console doctrine:migrations:migrate --no-interaction

# import test data fixtures
./bin/console doctrine:fixtures:load --no-interaction

# setup tests database
mysql -hdb -uroot -proot <<-EOQ
  CREATE DATABASE IF NOT EXISTS ${DB_NAME}; \
  GRANT ALL ON ${DB_NAME}.* TO "${DB_USER}"@'%' IDENTIFIED BY "${DB_USER}";
EOQ

(
  # setup test environment variables
  source .env.test

  # fully drop (if exists) and create application DB schema for test environment
  ./bin/console doctrine:schema:drop --env=test --full-database --force --no-interaction
  ./bin/console doctrine:migrations:migrate --env=test --no-interaction
)
