imports:
    - { resource: ../all/config.yml }
    - { resource: security.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/commons/development/routing.yml"
        strict_requirements: true

web_profiler:
    toolbar: true
    intercept_redirects: false