security:
    providers:
        database:
          entity: { class: Mealz\UserBundle\Entity\Login, property: username }

    firewalls:
        mealz:
            provider: database
            form_login:
                login_path:  MealzUserBundle_login
                check_path:  MealzUserBundle_checkLogin
