<?php

namespace Mealz\MealBundle\Entity;

/**
 * GuestInvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestInvitationRepository extends \Doctrine\ORM\EntityRepository
{
}
