version: '3.6'

services:
  mercure:
    image: dunglas/mercure
    container_name: ddev-${DDEV_SITENAME}-mercure
    restart: unless-stopped
    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    environment:
      MERCURE_PUBLISHER_JWT_ALG: HS256
      MERCURE_PUBLISHER_JWT_KEY: testing
      MERCURE_SUBSCRIBER_JWT_ALG: HS256
      MERCURE_SUBSCRIBER_JWT_KEY: testing
      HTTP_EXPOSE: '8080:8080'
      HTTPS_EXPOSE: '8081:8080'
      VIRTUAL_HOST: ${DDEV_HOSTNAME}
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    expose:
      - 8080
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile.dev

volumes:
  caddy_data:
  caddy_config:
