version: '3.6'

services:
  web:
    ports:
      - "1337:1337"
      - "2122:22"

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS
      # SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_ALG: HS256
      MERCURE_PUBLISHER_JWT_KEY: 'testing'
      MERCURE_SUBSCRIBER_JWT_ALG: HS256
      MERCURE_SUBSCRIBER_JWT_KEY: 'testing' 
    # Uncomment the following line to enable the development mode
    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    networks:
      default: null
    ports:
    - mode: ingress
      target: 80
      published: 2080
      protocol: tcp
    - mode: ingress
      target: 443
      published: 2443
      protocol: tcp
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

